version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"  # Host:5001 → Container:5001
    environment:
      - FLASK_ENV=development

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"  # Host:3000 → Container:3000
    environment:
      - REACT_APP_API_URL=http://localhost:5001  # Point to backend on port 5001
    depends_on:
      - backend