version: 1

services:
  # Backend Service (Flask API)
  - type: web
    name: hogwarts-backend
    plan: free
    docker:
      dockerfile: backend/Dockerfile
      context: .
    envVars:
      - key: FLASK_ENV
        value: production
    healthCheckPath: /api/points?window=all
    numInstances: 1

  # Frontend Service (React App)
  - type: web
    name: hogwarts-frontend
    plan: free
    docker:
      dockerfile: frontend/Dockerfile
      context: .
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: hogwarts-backend
          envVarKey: RENDER_EXTERNAL_URL
    numInstances: 1